### ISSUE TITLE
【デザインリニューアル】申請（一覧画面篇）

### ISSUE THREAD

**Issue by SofPyon** [SofPyon/inaka-portal#168]
## 背景

申請画面のデザインリニューアル＆Laravel 化をする。

ただ、申請機能周りのプログラムは複雑であり、またスパゲッティコード化しているため、この issue では、着手がしやすい申請一覧画面のみ Laravel 化を行う。

### デザインについて
新デザインの「スケジュール」ページ（ /schedules という URL でアクセス可能 ）が似ていると思うので、参考にしてください。

<img width="411" alt="inaka-portal_新デザイン" src="https://user-images.githubusercontent.com/6687653/71759763-6257ae00-2ef5-11ea-8043-7918cee9b48b.png">

### Action 設計について
各 URL は以下のようにしてください。「スケジュール」関係の Action と似ているので、そちらを参考に実装すると良いかと思います。

| URL | Actionの名前 | 説明 |
| --- | --- | --- |
| /forms | Forms\IndexAction | 申請一覧ページ |
| /forms/closed | Forms\ClosedAction | 受付終了した申請の一覧ページ |
| /forms/all | Forms\AllAction | 全申請一覧ページ（受付開始前・受付中・終了の全てを含む） |

### 「提出済」バッジについて
新デザインでは Bootstrap を利用していないので、独自にバッジをデザインする必要がある。

作成方法は以下の通り。

1. resources/sass/v2/modules/_badge.scss というファイルを作成する
1. resources/sass/v2/app.scss で、1. で作成したファイルを import する
1. _badge.scss ファイルの中身は以下のようにする（コメントは書かなくて大丈夫）
    ```scss
    .badge {
        // ここに badge 関連のスタイルを書く
        // display: inline-block にするのがおすすめ
        &.is-primary {
            background: $color-primary; // 青色
        }
        &.is-danger {
            background: $color-danger; // 赤色
        }
        &.is-success {
            background: $color-success; // 緑色
        }
        &.is-muted {
            background: $color-muted; // 灰色
        }
    }
    ```
1. バッジを HTML で使うには、以下のようにする
    ```html
    <span class="badge is-success">提出済</span>
    <span class="badge is-danger">再提出</span>
    <span class="badge is-muted">受付開始前</span>
    ```

### 団体セレクターについて
詳しい仕様についてはお任せします！
（お問い合わせページのように、一覧ページにドロップダウンをつけても良いし、先日作ってくれた団体セレクターを活用する形でも構いません）

※ 団体セレクターは新デザインにする必要はありません

### ビューファイルの扱いについて
新デザインの SCSS とビューは、`v2` というフォルダの中にファイルを作成しています。

- SCSS : `resources/sass/v2` フォルダ
- ビュー : `resources/views/v2` フォルダ
